# Generated by Django 3.1 on 2020-09-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['f_pub'], 'verbose_name': 'Publicaciones'},
        ),
    ]
